### ISSUE TITLE
(before="2023-06-01"|| after="2023-01-01") 使用报错，这个是api的问题嘛

### ISSUE THREAD

**Issue by RainClv** [10cks/fofaEX#10]
(before="2023-06-01"|| after="2023-01-01") 使用报错，这个是api的问题嘛

**Comment by 10cks** [comment]
这个语法貌似有问题

**Comment by RainClv** [comment]
我想查询某一个时间范围的资产，同时使用这个就会报错

**Comment by 10cks** [comment]
官网上执行这个，现在也报错

**Comment by RainClv** [comment]
正常使用是可以的，估计是api有问题
<img width="990" alt="image" src="https://github.com/10cks/fofaEX/assets/62876402/fd6ac677-fe91-42fc-bdec-e8f0cabacfab">

**Comment by 10cks** [comment]
八成是怕爬虫
