### ISSUE TITLE
多平台支持

### ISSUE THREAD

**Issue by duokebei** [10cks/fofaEX#3]
希望作者可以支持更多平台，常用的hunter、quake等等

**Comment by 10cks** [comment]
好的

**Comment by 10cks** [comment]
是的，导出数据是基础功能，集成各平台接口都会有这个功能

**Comment by 10cks** [comment]
> > 好的
> 
> 最好是都有数据导出为excel的功能，可以参考下fofa_view，谢谢师傅的阅读。

已支持文件导出和文件导入功能
