### ISSUE TITLE
默认查询数量修改完重开不保存

### ISSUE THREAD

**Issue by zipscan** [10cks/fofaEX#5]
建议能够保存修改完的默认查询数量，我与同事合买的包年高级号，多位同事共用最好要限查询量，每次重开会忘记修改。

**Comment by 10cks** [comment]
好的，已采纳

**Comment by 10cks** [comment]
最新pre版本已设置可独立保存查询数量、查询区间：https://github.com/10cks/fofaEX/releases/download/2.1/fofaEX_v2_1_pre.zip

**Comment by zipscan** [comment]
非常 好用，谢谢！

**Comment by 10cks** [comment]
> 非常 好用，谢谢！

可下载最新 v2.2版本，集成了插件模板功能，fofa扫描结果可使用httpx一键探活
