### ISSUE TITLE
mac插件模式点完没反应

### ISSUE THREAD

**Issue by wlaq-su** [10cks/fofaEX#6]

**Comment by 10cks** [comment]
需要去https://github.com/projectdiscovery/httpx官网下载对应的mac包，替换plugins/httpx 文件夹下的 httpx.exe文件，接着修改httpxSetting.json文件中的Path参数为"./plugins/httpx/httpx"即可。
记得给 mac 的httpx 对应运行权限，该功能已经过mac测试，可以正常使用。

**Comment by 10cks** [comment]
已更新 README 文档，师傅感兴趣的话可以加入内测群进行问题反馈。
https://github.com/10cks/fofaEX/blob/master/README.md#%E5%AD%A6%E4%B9%A0%E4%BA%A4%E6%B5%81

**Comment by wlaq-su** [comment]
> https://github.com/projectdiscovery/httpx

改完配置了还是不行，显示没有插件

**Comment by 10cks** [comment]
应该是配置文件没写对，我上午刚用 mac 测试好，加我微信好友，github 交流有点麻烦

**Comment by 10cks** [comment]
你这个没给httpX权限，需要设置一下httpx的运行权限
